### ISSUE TITLE
replace wagi with spin

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/hippo#579]
https://www.fermyon.com/blog/introducing-spin

https://github.com/fermyon/spin/

**Comment by radu-matei** [comment]
A bit of context here.
Spin includes a Wagi executor for HTTP workloads, so any Wagi application is compatible with Spin (with the exception of modules that declare their own subroutes using the `_routes` function, which Spin does not handle and does not plan to).

So being able to run Spin (with the Wagi executor) instead of Wagi directly gives us all the improvements we have in Spin (like pre-instantiation, new workloads, like Redis, access to host Wasm implementations, to name a few), while keeping compatibility with existing applications.

**Comment by squillace** [comment]
I like this move a lot, and def agree to merge but I would ask us to give a day as I want to think about the project as a whole. Deislabs existence was to provide new projects to foster ecosystem growth, and either to move the tools out of the org or archive them, and we've kept to that. 

So I'd like the ability to think on the project and deislabs as a home for a day if you'd be willing here. Nothing wrong with the PR itself.

**Comment by devigned** [comment]
I believe using spin rather than wagi is an improvement for both the user and for the ongoing adoption of component model interfaces. Spin offers a more expressive and structured interface for user apps to target while also providing wagi support. 

👍

**Comment by devigned** [comment]
I believe using spin rather than wagi is an improvement for both the user and for the ongoing adoption of component model interfaces. Spin offers a more expressive and structured interface for user apps to target while also providing wagi support. 

👍

**Comment by squillace** [comment]
If that's the case, let's roll forward. @devigned have a look at the PR and approve to merge! @radu-matei @bacongobbler thanks!
