### ISSUE TITLE
return routes associated with spin app running in channel

### ISSUE THREAD

**Issue by michelleN** [deislabs/hippo#899]
It would be cool if the channel returned the routes associated with the channel with the specific scheme (http vs https) from the api.

**Comment by bacongobbler** [comment]
The UI currently accomplishes this via the Channel's `activeRevision.Components` object, with some logic to [check if the route ends with an ellipsis or not](https://github.com/deislabs/hippo/blob/11e0388c67135ede1923eb10e0f771a8d68bc931/src/Web/ClientApp/src/app/components/channel/overview/overview.component.ts#L63-L71).

https://github.com/deislabs/hippo/blob/main/src/Core/Entities/Revision.cs#L15

This endpoint has been available since Hippo v0.9.0.
